name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
env:
  IMAGE_NAME: www:$GITHUB_SHA

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: debug 1
      run: echo "Image name $env.IMAGE_NAME"

    - name: Build the Docker image
      run: docker build . --file Server/Dockerfile --tag ${{ env.IMAGE_NAME }}
  
    - name: Docker Image Artifact Upload
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: ${{ env.IMAGE_NAME }}
        retention_days: 0
